/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Wellington
 */
public class cadMedView extends javax.swing.JPanel {

    /**
     * Creates new form cadMedView
     */
    public cadMedView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTarja = new javax.swing.JLabel();
        txtNomeMed = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblValidade = new javax.swing.JLabel();
        txtValidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblDesc = new javax.swing.JLabel();
        cmbTipoMed = new javax.swing.JComboBox<>();
        cmbTarja = new javax.swing.JComboBox<>();
        lblNomeMed1 = new javax.swing.JLabel();
        lblTipoMed = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 249, 215));
        setPreferredSize(new java.awt.Dimension(600, 481));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTarja.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTarja.setText("TARJA:");
        add(lblTarja, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 80, 30));

        txtNomeMed.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtNomeMed.setText("jTextField1");
        add(txtNomeMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 460, 30));

        lblPreco.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblPreco.setText("PREÇO:");
        add(lblPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 80, 30));
        lblPreco.getAccessibleContext().setAccessibleName("PRECO");

        txtPreco.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtPreco.setText("jTextField1");
        add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 140, 30));

        lblValidade.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblValidade.setText("VALIDADE:");
        add(lblValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 30));

        txtValidade.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtValidade.setText("jTextField1");
        add(txtValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 140, 30));

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 520, 100));

        lblDesc.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblDesc.setText("DESCRIÇÃO:");
        add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 30));

        cmbTipoMed.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cmbTipoMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbTipoMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 30));

        cmbTarja.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cmbTarja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbTarja, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 30));

        lblNomeMed1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblNomeMed1.setText("NOME:");
        add(lblNomeMed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 30));

        lblTipoMed.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTipoMed.setText("TIPO DE MEDICAMENTO:");
        add(lblTipoMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        jButton1.setText("jButton1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jButton2.setText("jButton2");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jPanel1.setBackground(new java.awt.Color(40, 160, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adduser.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PESQUISAR");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOVO CADASTRO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(207, 207, 207)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel4)
                .addGap(148, 148, 148)
                .addComponent(jLabel3)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTarja;
    private javax.swing.JComboBox<String> cmbTipoMed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblNomeMed1;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTarja;
    private javax.swing.JLabel lblTipoMed;
    private javax.swing.JLabel lblValidade;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtNomeMed;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}
